### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by iuroc** [vanjs-org/converter#3]
I am developing a Node.js backend project using TypeScript, and my `tsconfig.json` looks like this:

```json
{
    "compilerOptions": {
        "strict": true,
        "outDir": "js",
        "target": "ESNext",
        "moduleResolution": "NodeNext",
        "module": "NodeNext"
    }
}
```

I am using the vanjs-converter in the following way:

```typescript
let { code, tags } = (await import('vanjs-converter')).htmlToVanCode(htmlCode, { skipEmptyText: true });
```

Then I encounter the following error: 
![image](https://github.com/vanjs-org/converter/assets/61752998/a835af50-e4de-4b60-863b-2e6339253cf7)

**Comment by Tao-VanJS** [comment]
Did you import the dependency `"@types/marked"`?

https://github.com/vanjs-org/converter/blob/80fcd809d8aaca4e4f6e4570dd4c96bf45ebbe2a/package.json#L44C5-L44C20

**Comment by iuroc** [comment]
I import vanjs-converter as a module, and theoretically, there is no need to separately install the development dependencies of vanjs-converter. Instead, I believe the issue lies in the way TypeScript modules are imported and the TypeScript compilation configuration. This only results in an error prompt but does not hinder the normal usage of the application.

**Comment by Tao-VanJS** [comment]
> I import vanjs-converter as a module, and theoretically, there is no need to separately install the development dependencies of vanjs-converter. Instead, I believe the issue lies in the way TypeScript modules are imported and the TypeScript compilation configuration. This only results in an error prompt but does not hinder the normal usage of the application.

Do you have a link for a repo that can reproduce the problem? I would like to try some fix and see if the fix can resolve the issue on your end.

I believe changing `moduleResolution` to `Bundler` will make it work but needs the confirmation. Also, I would like to explore how to make it work if `moduleResolution` is `NodeNext`.

**Comment by iuroc** [comment]
I added a configuration, `"skipLibCheck": true`, which perfectly resolved the errors in the Node.js + TypeScript environment (although it reduces the strictness of some constraints, fortunately, the code can now be compiled and run normally). The corrected `tsconfig.json` is as follows:

```json
{
    "compilerOptions": {
        "strict": true,
        "outDir": "js",
        "lib": [
            "ESNext",
            "DOM"
        ],
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "skipLibCheck": true
    }
}
```
